In [1]:
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules
data = pd.read_csv("Team_Sports_Survey_Preprocessed.csv")

In [2]:
# Get the age group which is below 18
age_group = data[data["Age Group"] == "18 <"]

In [3]:
# Split the values into a single items
age_group["Preferred Beach Activities"] = age_group["Preferred Beach Activities"].str.split(",")

# Convert the items into a transactional data 
transactions = age_group["Preferred Beach Activities"].explode().str.strip().reset_index() # seperate rows
transactions_encoded = transactions.pivot_table(index="index", columns="Preferred Beach Activities", aggfunc=lambda x: 1, fill_value=0)

C:\Users\joaqu\AppData\Local\Temp\ipykernel_28212\3879743949.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  age_group["Preferred Beach Activities"] = age_group["Preferred Beach Activities"].str.split(",")

In [4]:
# Use Apriori algorithm to find frequent association
frequent_items= apriori(transactions_encoded, min_support=0.3, use_colnames=True)
rule = association_rules(frequent_items)
rule[['antecedents','consequents','support', 'confidence', 'lift']].sort_values("confidence", ascending=False)

C:\Users\joaqu\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

,antecedents,consequents,support,confidence,lift
6,"(Beach Swimming, Surfboarding)",(Jetskiing),0.357143,1.000000,1.750000
7,"(Jetskiing, Surfboarding)",(Beach Swimming),0.357143,1.000000,1.750000
11,"(Snorkeling/Scuba Diving, Jetskiing)",(Kayaking/Paddling),0.357143,1.000000,1.400000
1,(Jetskiing),(Kayaking/Paddling),0.500000,0.875000,1.225000
0,(Surfboarding),(Beach Swimming),0.357143,0.833333,1.458333
2,(Surfboarding),(Jetskiing),0.357143,0.833333,1.458333
3,"(Kayaking/Paddling, Beach Swimming)",(Jetskiing),0.357143,0.833333,1.458333
4,"(Beach Swimming, Jetskiing)",(Kayaking/Paddling),0.357143,0.833333,1.166667
5,"(Beach Swimming, Jetskiing)",(Surfboarding),0.357143,0.833333,1.944444
8,(Surfboarding),"(Beach Swimming, Jetskiing)",0.357143,0.833333,1.944444
9,"(Snorkeling/Scuba Diving, Beach Swimming)",(Kayaking/Paddling),0.357143,0.833333,1.166667
10,"(Kayaking/Paddling, Beach Swimming)",(Snorkeling/Scuba Diving),0.357143,0.833333,1.296296